/**
 * Persona and stage per library slug, from `docs/library-r2-key-map.json` (`entries[].segment`,
 * `entries[].stage`). Ids match `@ifn/ui` `LIBRARY_PERSONAS` (landing taxonomy): the map's
 * `global-expansion` segment is normalized to `global_expansion`. Regenerate when the map
 * changes; `library-placement.test.ts` fails on drift.
 */
import type { LibraryPersonaId } from "@ifn/ui";

export type LibraryPlacement = {
  personaId: LibraryPersonaId;
  stageId: string;
};

export const LIBRARY_PLACEMENTS: Readonly<Record<string, LibraryPlacement>> = {
  "visa-pathways": { personaId: "global", stageId: "pre-arrival" },
  "entity-selection": { personaId: "aspiring", stageId: "commitment" },
  "austin-ecosystem-map": { personaId: "aspiring", stageId: "exploration" },
  "austin-relocation": { personaId: "global", stageId: "landing" },
  "banking-non-citizens": { personaId: "global", stageId: "landing" },
  "banking-setup": { personaId: "aspiring", stageId: "launch-readiness" },
  "biz-model-canvas": { personaId: "startups", stageId: "ideation" },
  "biz-plan-builder": { personaId: "smbs", stageId: "planning" },
  "board-toolkit": { personaId: "startups", stageId: "scale" },
  "bookkeeping-setup": { personaId: "smbs", stageId: "establish" },
  "build-vs-buy": { personaId: "startups", stageId: "mvp" },
  "business-gc-pathways": { personaId: "global", stageId: "thriving" },
  "cap-table-guide": { personaId: "startups", stageId: "growth" },
  "cash-flow-template": { personaId: "smbs", stageId: "establish" },
  "city-selection": { personaId: "global", stageId: "pre-arrival" },
  "co-founder-scorecard": { personaId: "aspiring", stageId: "commitment" },
  "cohort-analysis": { personaId: "startups", stageId: "pmf" },
  "comp-analysis": { personaId: "aspiring", stageId: "validation" },
  "comp-mapping": { personaId: "startups", stageId: "ideation" },
  "credit-building": { personaId: "global", stageId: "establishing" },
  "customer-discovery-guide": { personaId: "aspiring", stageId: "validation" },
  "dual-entity": { personaId: "global", stageId: "growing" },
  "due-diligence": { personaId: "startups", stageId: "exit" },
  "ein-registration": { personaId: "global", stageId: "landing" },
  "employment-law": { personaId: "global", stageId: "establishing" },
  "eng-scaling": { personaId: "startups", stageId: "scale" },
  "enterprise-sales": { personaId: "startups", stageId: "scale" },
  "entry-strategy-guide": { personaId: "global_expansion", stageId: "market-selection" },
  "financial-health": { personaId: "smbs", stageId: "optimize" },
  "first-10-hires": { personaId: "startups", stageId: "growth" },
  "first-100-users": { personaId: "startups", stageId: "mvp" },
  "first-30-days": { personaId: "aspiring", stageId: "launch-readiness" },
  "founder-assessment": { personaId: "aspiring", stageId: "exploration" },
  "founder-prenup": { personaId: "aspiring", stageId: "commitment" },
  "franchise-eval": { personaId: "smbs", stageId: "expand" },
  "fundraising-101": { personaId: "startups", stageId: "growth" },
  "global-entity-structures": { personaId: "global_expansion", stageId: "entity-compliance" },
  "global-team-ops": { personaId: "global_expansion", stageId: "scale-optimize" },
  "grand-opening-mktg": { personaId: "smbs", stageId: "launch" },
  "green-card-sponsorship": { personaId: "global", stageId: "growing" },
  "gtm-strategy": { personaId: "global", stageId: "establishing" },
  "hiring-checklist": { personaId: "smbs", stageId: "establish" },
  "ideation-milestones": { personaId: "startups", stageId: "ideation" },
  "intl-estate-planning": { personaId: "global", stageId: "thriving" },
  "intl-fundraising": { personaId: "global", stageId: "growing" },
  "investor-tracker": { personaId: "startups", stageId: "growth" },
  "ip-protection": { personaId: "global", stageId: "establishing" },
  "ipo-roadmap": { personaId: "startups", stageId: "exit" },
  "landing-page-mvp": { personaId: "aspiring", stageId: "validation" },
  "leap-decision-matrix": { personaId: "aspiring", stageId: "exploration" },
  "legal-counsel-eval": { personaId: "global", stageId: "landing" },
  "licensing-checklist": { personaId: "smbs", stageId: "planning" },
  "local-seo-setup": { personaId: "smbs", stageId: "launch" },
  "localization-checklist": { personaId: "global_expansion", stageId: "launch-localization" },
  "ma-overview": { personaId: "startups", stageId: "exit" },
  "market-eval-framework": { personaId: "global_expansion", stageId: "market-research" },
  "market-opp-guide": { personaId: "startups", stageId: "ideation" },
  "market-research-abroad": { personaId: "global", stageId: "pre-arrival" },
  "market-sizing-calc": { personaId: "aspiring", stageId: "validation" },
  "mktg-automation": { personaId: "smbs", stageId: "optimize" },
  "monetization-playbook": { personaId: "startups", stageId: "pmf" },
  "multi-country-ops": { personaId: "global", stageId: "thriving" },
  "multi-location": { personaId: "smbs", stageId: "expand" },
  "mvp-budget": { personaId: "startups", stageId: "mvp" },
  "mvp-scoping": { personaId: "startups", stageId: "mvp" },
  "network-building": { personaId: "aspiring", stageId: "launch-readiness" },
  "ops-audit": { personaId: "smbs", stageId: "optimize" },
  "partnership-guide": { personaId: "smbs", stageId: "expand" },
  "pitch-deck-template": { personaId: "startups", stageId: "growth" },
  "pivot-framework": { personaId: "startups", stageId: "pmf" },
  "pmf-dashboard": { personaId: "startups", stageId: "pmf" },
  "pmf-survey": { personaId: "startups", stageId: "pmf" },
  "post-exit-planning": { personaId: "startups", stageId: "exit" },
  "pre-arrival-financial": { personaId: "global", stageId: "pre-arrival" },
  "pricing-worksheet": { personaId: "smbs", stageId: "launch" },
  "problem-solution-fit": { personaId: "startups", stageId: "ideation" },
  "problem-solving-framework": { personaId: "aspiring", stageId: "exploration" },
  "product-expansion": { personaId: "smbs", stageId: "expand" },
  "professional-network": { personaId: "global", stageId: "growing" },
  "registration-checklist": { personaId: "aspiring", stageId: "launch-readiness" },
  "regulatory-env": { personaId: "global", stageId: "establishing" },
  "remote-entity": { personaId: "global", stageId: "pre-arrival" },
  "retention-playbook": { personaId: "smbs", stageId: "establish" },
  "runway-calc": { personaId: "aspiring", stageId: "commitment" },
  "sba-loan-guide": { personaId: "smbs", stageId: "planning" },
  "scaling-ops": { personaId: "startups", stageId: "scale" },
  "scaling-states": { personaId: "global", stageId: "growing" },
  "secondary-sales": { personaId: "startups", stageId: "exit" },
  "series-a-ready": { personaId: "startups", stageId: "scale" },
  "smb-customer-acq": { personaId: "smbs", stageId: "launch" },
  "smb-entity-guide": { personaId: "smbs", stageId: "planning" },
  "smb-funding-options": { personaId: "smbs", stageId: "planning" },
  "smb-tax-strategy": { personaId: "smbs", stageId: "optimize" },
  "sop-template": { personaId: "smbs", stageId: "establish" },
  "ssn-itin-guide": { personaId: "global", stageId: "landing" },
  "startup-cost-est": { personaId: "smbs", stageId: "planning" },
  "state-env-compare": { personaId: "global", stageId: "landing" },
  "succession-toolkit": { personaId: "smbs", stageId: "expand" },
  "tax-obligations": { personaId: "global", stageId: "growing" },
  "tech-arch-guide": { personaId: "startups", stageId: "mvp" },
  "tech-roadmap": { personaId: "smbs", stageId: "optimize" },
  "tech-stack-starter": { personaId: "aspiring", stageId: "launch-readiness" },
  "term-sheet-decoder": { personaId: "startups", stageId: "growth" },
  "transition-playbook": { personaId: "aspiring", stageId: "commitment" },
  "us-biz-culture": { personaId: "global", stageId: "pre-arrival" },
  "user-testing-scripts": { personaId: "startups", stageId: "mvp" },
  "validation-tracker": { personaId: "aspiring", stageId: "validation" },
  "vendor-eval": { personaId: "smbs", stageId: "launch" },
};

/** R2 map segment to `@ifn/ui` persona id. */
export function personaIdFromSegment(segment: string): string {
  return segment === "global-expansion" ? "global_expansion" : segment;
}

/** Placement for a bare slug, or `undefined` when the map does not know it. */
export function libraryPlacementForSlug(slug: string): LibraryPlacement | undefined {
  return LIBRARY_PLACEMENTS[slug];
}
