/** Auto-generated from 2026-09-26-library-r2-key-map.json — do not hand-edit. */
export const LIBRARY_DOC_VERSION = "v1.1" as const;

export type LibraryAssetKind = "pdf" | "xlsx";

export type LibrarySerialEntry = {
  nnn: string;
  slug: string;
  kind: LibraryAssetKind;
};

/** Pack A first (001–003), then remaining seed ids sorted A→Z (004+). */
export const LIBRARY_SERIALS: readonly LibrarySerialEntry[] = [
  { nnn: "001", slug: "visa-pathways", kind: "pdf" },
  { nnn: "002", slug: "entity-selection", kind: "pdf" },
  { nnn: "003", slug: "austin-ecosystem-map", kind: "pdf" },
  { nnn: "004", slug: "austin-relocation", kind: "pdf" },
  { nnn: "005", slug: "banking-non-citizens", kind: "pdf" },
  { nnn: "006", slug: "banking-setup", kind: "pdf" },
  { nnn: "007", slug: "biz-model-canvas", kind: "pdf" },
  { nnn: "008", slug: "biz-plan-builder", kind: "xlsx" },
  { nnn: "009", slug: "board-toolkit", kind: "pdf" },
  { nnn: "010", slug: "bookkeeping-setup", kind: "pdf" },
  { nnn: "011", slug: "build-vs-buy", kind: "pdf" },
  { nnn: "012", slug: "business-gc-pathways", kind: "pdf" },
  { nnn: "013", slug: "cap-table-guide", kind: "pdf" },
  { nnn: "014", slug: "cash-flow-template", kind: "xlsx" },
  { nnn: "015", slug: "city-selection", kind: "pdf" },
  { nnn: "016", slug: "co-founder-scorecard", kind: "pdf" },
  { nnn: "017", slug: "cohort-analysis", kind: "pdf" },
  { nnn: "018", slug: "comp-analysis", kind: "pdf" },
  { nnn: "019", slug: "comp-mapping", kind: "pdf" },
  { nnn: "020", slug: "credit-building", kind: "pdf" },
  { nnn: "021", slug: "customer-discovery-guide", kind: "pdf" },
  { nnn: "022", slug: "dual-entity", kind: "pdf" },
  { nnn: "023", slug: "due-diligence", kind: "pdf" },
  { nnn: "024", slug: "ein-registration", kind: "pdf" },
  { nnn: "025", slug: "employment-law", kind: "pdf" },
  { nnn: "026", slug: "eng-scaling", kind: "pdf" },
  { nnn: "027", slug: "enterprise-sales", kind: "pdf" },
  { nnn: "028", slug: "entry-strategy-guide", kind: "pdf" },
  { nnn: "029", slug: "financial-health", kind: "xlsx" },
  { nnn: "030", slug: "first-10-hires", kind: "pdf" },
  { nnn: "031", slug: "first-100-users", kind: "pdf" },
  { nnn: "032", slug: "first-30-days", kind: "pdf" },
  { nnn: "033", slug: "founder-assessment", kind: "pdf" },
  { nnn: "034", slug: "founder-prenup", kind: "pdf" },
  { nnn: "035", slug: "franchise-eval", kind: "pdf" },
  { nnn: "036", slug: "fundraising-101", kind: "pdf" },
  { nnn: "037", slug: "global-entity-structures", kind: "pdf" },
  { nnn: "038", slug: "global-team-ops", kind: "pdf" },
  { nnn: "039", slug: "grand-opening-mktg", kind: "pdf" },
  { nnn: "040", slug: "green-card-sponsorship", kind: "pdf" },
  { nnn: "041", slug: "gtm-strategy", kind: "pdf" },
  { nnn: "042", slug: "hiring-checklist", kind: "pdf" },
  { nnn: "043", slug: "ideation-milestones", kind: "pdf" },
  { nnn: "044", slug: "intl-estate-planning", kind: "pdf" },
  { nnn: "045", slug: "intl-fundraising", kind: "pdf" },
  { nnn: "046", slug: "investor-tracker", kind: "xlsx" },
  { nnn: "047", slug: "ip-protection", kind: "pdf" },
  { nnn: "048", slug: "ipo-roadmap", kind: "pdf" },
  { nnn: "049", slug: "landing-page-mvp", kind: "pdf" },
  { nnn: "050", slug: "leap-decision-matrix", kind: "pdf" },
  { nnn: "051", slug: "legal-counsel-eval", kind: "pdf" },
  { nnn: "052", slug: "licensing-checklist", kind: "pdf" },
  { nnn: "053", slug: "local-seo-setup", kind: "pdf" },
  { nnn: "054", slug: "localization-checklist", kind: "pdf" },
  { nnn: "055", slug: "ma-overview", kind: "pdf" },
  { nnn: "056", slug: "market-eval-framework", kind: "xlsx" },
  { nnn: "057", slug: "market-opp-guide", kind: "pdf" },
  { nnn: "058", slug: "market-research-abroad", kind: "pdf" },
  { nnn: "059", slug: "market-sizing-calc", kind: "xlsx" },
  { nnn: "060", slug: "mktg-automation", kind: "pdf" },
  { nnn: "061", slug: "monetization-playbook", kind: "pdf" },
  { nnn: "062", slug: "multi-country-ops", kind: "pdf" },
  { nnn: "063", slug: "multi-location", kind: "pdf" },
  { nnn: "064", slug: "mvp-budget", kind: "xlsx" },
  { nnn: "065", slug: "mvp-scoping", kind: "pdf" },
  { nnn: "066", slug: "network-building", kind: "pdf" },
  { nnn: "067", slug: "ops-audit", kind: "pdf" },
  { nnn: "068", slug: "partnership-guide", kind: "pdf" },
  { nnn: "069", slug: "pitch-deck-template", kind: "pdf" },
  { nnn: "070", slug: "pivot-framework", kind: "pdf" },
  { nnn: "071", slug: "pmf-dashboard", kind: "xlsx" },
  { nnn: "072", slug: "pmf-survey", kind: "xlsx" },
  { nnn: "073", slug: "post-exit-planning", kind: "pdf" },
  { nnn: "074", slug: "pre-arrival-financial", kind: "pdf" },
  { nnn: "075", slug: "pricing-worksheet", kind: "pdf" },
  { nnn: "076", slug: "problem-solution-fit", kind: "pdf" },
  { nnn: "077", slug: "problem-solving-framework", kind: "xlsx" },
  { nnn: "078", slug: "product-expansion", kind: "xlsx" },
  { nnn: "079", slug: "professional-network", kind: "pdf" },
  { nnn: "080", slug: "registration-checklist", kind: "pdf" },
  { nnn: "081", slug: "regulatory-env", kind: "pdf" },
  { nnn: "082", slug: "remote-entity", kind: "pdf" },
  { nnn: "083", slug: "retention-playbook", kind: "pdf" },
  { nnn: "084", slug: "runway-calc", kind: "xlsx" },
  { nnn: "085", slug: "sba-loan-guide", kind: "pdf" },
  { nnn: "086", slug: "scaling-ops", kind: "pdf" },
  { nnn: "087", slug: "scaling-states", kind: "pdf" },
  { nnn: "088", slug: "secondary-sales", kind: "pdf" },
  { nnn: "089", slug: "series-a-ready", kind: "pdf" },
  { nnn: "090", slug: "smb-customer-acq", kind: "pdf" },
  { nnn: "091", slug: "smb-entity-guide", kind: "pdf" },
  { nnn: "092", slug: "smb-funding-options", kind: "pdf" },
  { nnn: "093", slug: "smb-tax-strategy", kind: "pdf" },
  { nnn: "094", slug: "sop-template", kind: "pdf" },
  { nnn: "095", slug: "ssn-itin-guide", kind: "pdf" },
  { nnn: "096", slug: "startup-cost-est", kind: "xlsx" },
  { nnn: "097", slug: "state-env-compare", kind: "pdf" },
  { nnn: "098", slug: "succession-toolkit", kind: "pdf" },
  { nnn: "099", slug: "tax-obligations", kind: "pdf" },
  { nnn: "100", slug: "tech-arch-guide", kind: "pdf" },
  { nnn: "101", slug: "tech-roadmap", kind: "pdf" },
  { nnn: "102", slug: "tech-stack-starter", kind: "pdf" },
  { nnn: "103", slug: "term-sheet-decoder", kind: "pdf" },
  { nnn: "104", slug: "transition-playbook", kind: "pdf" },
  { nnn: "105", slug: "us-biz-culture", kind: "pdf" },
  { nnn: "106", slug: "user-testing-scripts", kind: "pdf" },
  { nnn: "107", slug: "validation-tracker", kind: "xlsx" },
  { nnn: "108", slug: "vendor-eval", kind: "xlsx" },
] as const;

const BY_SLUG: ReadonlyMap<string, LibrarySerialEntry> = new Map(
  LIBRARY_SERIALS.map((e) => [e.slug, e]),
);

export function serialForSlug(slug: string): LibrarySerialEntry | undefined {
  return BY_SLUG.get(slug);
}

export function libraryFolder(nnn: string, slug: string): string {
  return `library/${nnn}-${slug}`;
}
